### ISSUE TITLE
Renderer / OrbitCtrl causes issue

### ISSUE THREAD

**Issue by krumpyzoid** [troisjs/nuxt3-test#1]
It's me again ...

I used your starter to try out my component and I still get the issue.

```
Must use import to load ES Module: C:\Users\mathi\Downloads\nuxt3-test-master\nuxt3-test-master\.output\server\node_modules\three\examples\jsm\controls\OrbitControls.js
require() of ES modules is not supported.
require() of C:\Users\mathi\Downloads\nuxt3-test-master\nuxt3-test-master\.output\server\node_modules\three\examples\jsm\controls\OrbitControls.js from C:\Users\mathi\Downloads\nuxt3-test-master\nuxt3-test-master\.output\server\node_modules\troisjs\build\trois.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename OrbitControls.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\mathi\Downloads\nuxt3-test-master\nuxt3-test-master\.output\server\node_modules\three\examples\jsm\package.json.

  require() of C:\Users\mathi\Downloads\nuxt3-test-master\nuxt3-test-master\.output\server\node_modules\three\examples\jsm\controls\OrbitControls.js from C:\Users\mathi\Downloads\nuxt3-test-master\nuxt3-test-master\.output\server\node_modules\troisjs\build\trois.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
  at new NodeError (internal/errors.js:322:7)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13) 
  at Module.load (internal/modules/cjs/loader.js:950:32)
  at Function.Module._load (internal/modules/cjs/loader.js:790:12)
  at Module.require (internal/modules/cjs/loader.js:974:19)
  at require (internal/modules/cjs/helpers.js:93:18)
  at Object.<anonymous> (C:\Users\mathi\Downloads\nuxt3-test-master\nuxt3-test-master\.output\server\node_modules\troisjs\build\trois.js:7:24)
  at Module._compile (internal/modules/cjs/loader.js:1085:14)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) 
  at Module.load (internal/modules/cjs/loader.js:950:32)
(node:19840) UnhandledPromiseRejectionWarning: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\mathi\Downloads\nuxt3-test-master\nuxt3-test-master\.output\server\node_modules\three\examples\jsm\controls\OrbitControls.js
require() of ES modules is not supported.
require() of C:\Users\mathi\Downloads\nuxt3-test-master\nuxt3-test-master\.output\server\node_modules\three\examples\jsm\controls\OrbitControls.js from C:\Users\mathi\Downloads\nuxt3-test-master\nuxt3-test-master\.output\server\node_modules\troisjs\build\trois.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename OrbitControls.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\mathi\Downloads\nuxt3-test-master\nuxt3-test-master\.output\server\node_modules\three\examples\jsm\package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (C:\Users\mathi\Downloads\nuxt3-test-master\nuxt3-test-master\.output\server\node_modules\troisjs\build\trois.js:7:24)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19840) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Must use import to load ES Module: C:\Users\mathi\Downloads\nuxt3-test-master\nuxt3-test-master\.output\server\node_modules\three\examples\jsm\controls\OrbitControls.js
require() of ES modules is not supported.
require() of C:\Users\mathi\Downloads\nuxt3-test-master\nuxt3-test-master\.output\server\node_modules\three\examples\jsm\controls\OrbitControls.js from C:\Users\mathi\Downloads\nuxt3-test-master\nuxt3-test-master\.output\server\node_modules\troisjs\build\trois.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename OrbitControls.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\mathi\Downloads\nuxt3-test-master\nuxt3-test-master\.output\server\node_modules\three\examples\jsm\package.json.

  require() of C:\Users\mathi\Downloads\nuxt3-test-master\nuxt3-test-master\.output\server\node_modules\three\examples\jsm\controls\OrbitControls.js from C:\Users\mathi\Downloads\nuxt3-test-master\nuxt3-test-master\.output\server\node_modules\troisjs\build\trois.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
  at new NodeError (internal/errors.js:322:7)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13) 
  at Module.load (internal/modules/cjs/loader.js:950:32)
  at Function.Module._load (internal/modules/cjs/loader.js:790:12)
  at Module.require (internal/modules/cjs/loader.js:974:19)
  at require (internal/modules/cjs/helpers.js:93:18)
  at Object.<anonymous> (C:\Users\mathi\Downloads\nuxt3-test-master\nuxt3-test-master\.output\server\node_modules\troisjs\build\trois.js:7:24)
  at Module._compile (internal/modules/cjs/loader.js:1085:14)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) 
  at Module.load (internal/modules/cjs/loader.js:950:32)
(node:19840) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
```

I haven't changed anything except the content of Test.vue with my component
```
<template>
<div style="display: flex; justify-content: center; align-items: center;">
    <div style="width: 800px; height: 800px">
    <Renderer ref="renderer" :alpha="true" :resize="true" :orbitCtrl="{active: true, enableZoom: false}">
    <Camera :position="{ z: 7 }" />
    <Scene :background="'#E8E6DE'">
      <PointLight :position="{ y: 50, z: 50 }" />
      <Mesh ref="box">
            <TorusKnotGeometry :radius="1.5" :tube="0.625" :tubularSegments="300" :radialSegments="200" />
            <ToonMaterial :color="'#0F161B'" />
        </Mesh>
    </Scene>
    <EffectComposer>
      <RenderPass />
      <FXAAPass />
    </EffectComposer>
  </Renderer>
    </div>
</div>
</template>

<script>
  import { Mesh, Camera, PointLight, Renderer, Scene, TorusKnotGeometry, EffectComposer, RenderPass, FXAAPass, ToonMaterial } from 'troisjs'

export default {
    components: { Mesh, Camera, PointLight, Renderer, Scene, TorusKnotGeometry, EffectComposer, RenderPass, FXAAPass, ToonMaterial },
    data() {
        return {
        }
    },
    methods: {
      
    },
    mounted() {
      const renderer = this.$refs.renderer;
      const box = this.$refs.box.mesh;
      renderer.onBeforeRender(() => {
        box.rotation.x += 0.003;
      })
      },
}

</script>
<style lang="scss">
</style>
```

**Comment by klevron** [comment]
Are you sure you are using ClientOnly ?

**Comment by klevron** [comment]
Sorry I was using ClientOnly in the wrong way, it works now : https://nuxt3-test-five.vercel.app/
As stated in Nuxt docs about `ClientOnly` : _register the component in a client-side only plugin_
Please check this : https://github.com/troisjs/nuxt3-test/tree/master/plugins
